default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: Axike
  password: password
  host: localhost
  port: 3306
  database: WacCraft

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default